stages:
  - deploy

deploy_backend:
  stage: deploy
  only:
    - main

  before_script:
    - apt-get update -y
    - apt-get install -y openssh-client rsync
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts

  script:
    - export RELEASE=$(date +%s)

    # create release directory
    - ssh $EC2_USER@$EC2_HOST "mkdir -p $PROJECT_PATH/releases/$RELEASE"

    # sync files to EC2
    - rsync -az --delete --exclude='.git' --exclude='gitlab-deploy' --exclude='gitlab-deploy.pub' ./ $EC2_USER@$EC2_HOST:$PROJECT_PATH/releases/$RELEASE

    # install backend dependencies and restart server
    - ssh $EC2_USER@$EC2_HOST "
        cd $PROJECT_PATH/releases/$RELEASE/backend &&
        npm ci --omit=dev &&
        ln -sfn $PROJECT_PATH/releases/$RELEASE $PROJECT_PATH/current &&
        pm2 reload server || pm2 start $PROJECT_PATH/current/backend/src/server.js --name server
      "